Update ErrorHandlingResultCallback#onResult log level
When the log appender to the "org.mongodb" package is configured with ERROR level.

```xml
<logger name="org.mongodb" level="ERROR"/>
```

And some exception is thrown inside the callback lambda expression body.

```java
...
mongoCollection.insertOne(document, (result, error) -> {
        if (null == error) {
          // do something that throws some runtime exception.
          throw new RuntimeException("some exception!!!");
        }
      });
```

Nothing is written to the log by shadowing the error that occurred. 
Because internally the driver writes as warning and not error. ErrorHandlingResultCallback#onResult

```log
2018-01-09 12:57:28,427 [Thread-5] WARN  o.m.d.client - Callback onResult call produced an error 
java.lang.RuntimeException: some exception!!!
	at Mongo$MongoService.lambda$insertOne$2(Mongo.java:407)
	at com.mongodb.async.client.MongoCollectionImpl$1.onResult(MongoCollectionImpl.java:527)
	at com.mongodb.async.client.MongoCollectionImpl$1.onResult(MongoCollectionImpl.java:524)
	at com.mongodb.async.client.MongoCollectionImpl$9.onResult(MongoCollectionImpl.java:1132)
	at com.mongodb.async.client.MongoCollectionImpl$9.onResult(MongoCollectionImpl.java:1116)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	....
```