When checking the presence of slf4j, ClassNotFoundException isn't enough
I'm getting a java.lang.NoClassDefFoundError: org/apache/log4j/Level
because I use org.apache.logging.log4j.Level